Document: ibus-libzhuyin
Title: Debian ibus-libzhuyin Manual
Author: <insert document author here>
Abstract: This manual describes what ibus-libzhuyin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ibus-libzhuyin/ibus-libzhuyin.sgml.gz

Format: postscript
Files: /usr/share/doc/ibus-libzhuyin/ibus-libzhuyin.ps.gz

Format: text
Files: /usr/share/doc/ibus-libzhuyin/ibus-libzhuyin.text.gz

Format: HTML
Index: /usr/share/doc/ibus-libzhuyin/html/index.html
Files: /usr/share/doc/ibus-libzhuyin/html/*.html
